[2025-07-25T19:15:35.022+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T19:15:35.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dnc_pipeline.executar_pipeline_etl manual__2025-07-25T19:15:33.965405+00:00 [queued]>
[2025-07-25T19:15:35.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dnc_pipeline.executar_pipeline_etl manual__2025-07-25T19:15:33.965405+00:00 [queued]>
[2025-07-25T19:15:35.043+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-25T19:15:35.054+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): executar_pipeline_etl> on 2025-07-25 19:15:33.965405+00:00
[2025-07-25T19:15:35.057+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2025-07-25T19:15:35.060+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dnc_pipeline', 'executar_pipeline_etl', 'manual__2025-07-25T19:15:33.965405+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dnc_pipeline_dag.py', '--cfg-path', '/tmp/tmpy7x_zvvg']
[2025-07-25T19:15:35.061+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask executar_pipeline_etl
[2025-07-25T19:15:35.090+0000] {task_command.py:426} INFO - Running <TaskInstance: dnc_pipeline.executar_pipeline_etl manual__2025-07-25T19:15:33.965405+00:00 [running]> on host 5c057e95fc1d
[2025-07-25T19:15:35.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dnc_pipeline' AIRFLOW_CTX_TASK_ID='executar_pipeline_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T19:15:33.965405+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T19:15:33.965405+00:00'
[2025-07-25T19:15:35.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T19:15:35.267+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-07-25T19:15:37.648+0000] {credentials.py:567} INFO - Found credentials in environment variables.
[2025-07-25T19:15:40.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T19:15:40.153+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 22, in run_etl
    df_silver = df_bronze.dropna(subset=["user_id", "signup_date", "age", "subscription_status"]).copy()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6418, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['user_id', 'age']
[2025-07-25T19:15:40.161+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dnc_pipeline, task_id=executar_pipeline_etl, run_id=manual__2025-07-25T19:15:33.965405+00:00, execution_date=20250725T191533, start_date=20250725T191535, end_date=20250725T191540
[2025-07-25T19:15:40.169+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task executar_pipeline_etl (['user_id', 'age']; 193)
[2025-07-25T19:15:40.188+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T19:15:40.195+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T19:15:40.196+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
